### ISSUE TITLE
Serverless Function (memory and maxDuration) configuration is not available

### ISSUE THREAD

**Issue by NPCDW** [vercel-community/rust#109]
[My project configuration](https://github.com/NPCDW/vercel-rs/blob/master/vercel.json#L5-L6)
![image](https://github.com/vercel-community/rust/assets/32638459/6d8bc72c-6cc6-47d9-9404-c8b577197f19)

Displayed after deployment:
![image](https://github.com/vercel-community/rust/assets/32638459/1e56426e-ddbf-491a-9956-5754b116c827)

[Memory configuration instructions](https://vercel.com/docs/concepts/projects/project-configuration#value-definition)
![image](https://github.com/vercel-community/rust/assets/32638459/bf6944b1-5c6a-4eca-bc28-a34cc43b65d8)

**Comment by ecklf** [comment]
Good point, those values are currently not being passed when creating the resources. Should be an easy fix 🙏

**Comment by ecklf** [comment]
This is now shipped. Note that you need to keep the route order correct and specify the runtime property for each function path. Will work on an example if needed.

**Comment by NPCDW** [comment]
Thanks a lot for your contribution, now `memory` and `maxDuration` are working
