### ISSUE TITLE
How would I use this with other Rust web crate?

### ISSUE THREAD

**Issue by ManicMarrc** [vercel-community/rust#119]
How would I use this with another web crate like [Actix](https://actix.rs/) or [Rocket](https://rocket.rs/)?

**Comment by ecklf** [comment]
This runtime builds on top of tower so you'd need to use the exposed `ServiceBuilder` to hook in your framework. This [repo](https://github.com/lazear/axum-aws-lambda) would be an example for axum

Once you have that implementation you also need to add rewrites to your `vercel.json`

```
{
  "rewrites": [{ "source": "/api/(.*)", "destination": "/api/handler" }]
}
```

**Comment by abhemanyus** [comment]
@ecklf Is this still valid?

**Comment by abhemanyus** [comment]
Figured it out https://github.com/abhemanyus/vercel-axum-router
Don't know how I feel about the modifications I had to do to lib.rs, though. You'd do me a solid by taking a look at it.
