### ISSUE TITLE
Add support for watch mode in dev server

### ISSUE THREAD

**Issue by elcharitas** [vercel-community/rust#138]
Currently, you have to run `vercel dev` each time a change is made to the code.
It would be super nice if the server can watch for changes in filesystem and restart

**Comment by ecklf** [comment]
This is definitely working for me here (see screenshot for vc version). Feel free to reopen if the issue still exists.
![CleanShot 2024-04-04 at 10 39 53@2x](https://github.com/vercel-community/rust/assets/8146736/a0926cbc-5ecd-43f1-b049-5d20bf9671c8)
