### ISSUE TITLE
Tutorial leads to "NOT_FOUND" deployment

### ISSUE THREAD

**Issue by test3211234** [vercel-community/rust#142]
I'm new to Vercel, and wanted to use it in Rust. However, something in your README.md tutorial must be wrong or missing as this is what happens after following it and deploying it: 

![image](https://github.com/vercel-community/rust/assets/132314092/29fa83b8-2289-4105-afc2-9597449e103b)

You also never spoke about these:

![image](https://github.com/vercel-community/rust/assets/132314092/21cf6072-2c5b-4313-98de-0502bdebcbac)

I notice you never spoke about a package.json too, even though it's in your examples. I copy pasted it, and it made no difference. Also, is this project dead? I don't see many updates.

**Comment by Zxilly** [comment]
I use rewrite to route the traffic, see https://github.com/Zxilly/OnedriveHostsGenerator/blob/master/vercel.json

**Comment by dglsparsons** [comment]
Hey, not a dead project at all. It's just not under active development at the moment, and is a community effort. 

The Build & Development Settings are not needed for the Rust Runtime. 

Could you share a link to your deployment, so I can investigate? I suspect it could be the rewrites, but I'm not sure. 

Thanks 🙏

**Comment by TraceLD** [comment]
@test3211234 This is because by default the router uses directory structure based routing so your function is at `localhost:3000/api/handler`.

**Comment by loopassembly** [comment]
I had the same issue, and this configuration helped me. Thanks to @Zxilly !
```json{
    "outputDirectory": "public",
    "functions": {
      "api/**/*.rs": {
        "runtime": "vercel-rust@4.0.6"
      }
    },
    "rewrites": [
      {
        "source": "/(.*)",
        "destination": "/api/handler"
      }
    ]
  }```
