### ISSUE TITLE
Endpoints starting with 'm', 'a', 'i' or 'n' not included when using API bundling

### ISSUE THREAD

**Issue by Benjamin-Davies** [vercel-community/rust#144]
When using the experimental API bundling, creating files whose name starts with 'm', 'a', 'i' or 'n' are ignored and not included in the build.

# Steps to reproduce

- Clone this repo and navigate to `examples/route-merge/`.
- Append `syntax error` to the end of `foo.rs`.
- Run `cargo check`. It should detect the syntax error.
- Rename `foo.rs` to `a.rs`.
- Run `cargo check` again.

Current behavior: `a.rs` is not detected as a route and the syntax error is not detected.
Expected behavior: `a.rs` should be detected as a route and the syntax error should be shown again.

# Suspected cause

`vercel_runtime_macro/src/lib.rs` line 52 ([here](https://github.com/vercel-community/rust/blob/29ed32faf4f793d1c12f613d4641de3d112061b5/crates/vercel_runtime_macro/src/lib.rs#L52)) uses a glob that includes the negated character class `[!main]` which matches all characters except for 'm', 'a', 'i' or 'n'. I think the intended behavior was for it to match all filenames except for `main.rs`.

**Comment by dglsparsons** [comment]
Hi, thanks for raising this. 

The suspected cause is spot on! 

Feel free to open a PR if you have the time.
