### ISSUE TITLE
Looking for example with an index route and [id].rs

### ISSUE THREAD

**Issue by abcd-ca** [vercel-community/rust#149]
In NextJS for example, we can have routes defined with file paths,

```
/api/event/index.js
/api/event/[id].js
```

accessed in the url respectively as,

```
/api/event
/api/event/123
```

I can't figure out what the index route Rust file should be called. I tried `index.rs` and `mod.rs` but in both cases I had to add that to the URL. I want to be able to define index.rs but omit it in the url.

Thank you

**Comment by dglsparsons** [comment]
Looking at the routing code, I don't believe we special case anything for this pattern. 

Would it not work having 
`/api/event.rs` and `api/event/[id].rs` though?

**Comment by abcd-ca** [comment]
@dglsparsons Yes, that does the trick, thank you.
