### ISSUE TITLE
Prod deployment issue. Invalid runtime error

### ISSUE THREAD

**Issue by abcd-ca** [vercel-community/rust#150]
I have my project working locally (running with `vercel dev` but when I deploy (`vercel --prod`), the build gets stuck here:

```
Error: The following Serverless Functions contain an invalid "runtime":
  - api/calendar/event/[id] (provided)
  - api/calendar/event (provided). Learn More: https://vercel.com/guides/serverless-function-contains-invalid-runtime-error
```

Any insight would be appreciated.

**Comment by DervexDev** [comment]
Same problem here

**Comment by DervexDev** [comment]
Figured it out. You have to downgrade your project's Node.js version from `20.x` to `18.x`.

**Comment by abcd-ca** [comment]
@DervexDev Ah, good one for figuring that out! I'm going to create a documentation PR.
