### ISSUE TITLE
`vercel dev` still results to release build of rust

### ISSUE THREAD

**Issue by Zxilly** [vercel-community/rust#167]
Seems the debug build only be enabled if `VERCEL_BUILDER_DEBUG` was set. But I think `vercel` cli won't set this. We need other way to know which mode we are running.

https://github.com/vercel-community/rust/blob/954bdba290266de5831f7606122909667fc64249/src/index.ts#L36

https://github.com/vercel-community/rust/blob/954bdba290266de5831f7606122909667fc64249/src/index.ts#L71-L81

Set this env manully won't be good idea as it produces lot of unnecessary log.

**Comment by ecklf** [comment]
Shipped in `4.0.8`

**Comment by Zxilly** [comment]
Please keep this open file a while, as I think the cache mechanism for the `dev` may be also corrupted. I will dive into it.
