### ISSUE TITLE
Only `api/**/*.rs` can trigger a rebuild during dev

### ISSUE THREAD

**Issue by Zxilly** [vercel-community/rust#171]
As repo https://github.com/Zxilly/data2image described, some files located in the `src` folder, update these files won't trigger a rebuild.

With debug logging

```
> [debug] [2024-07-19T19:56:25.493Z] Ignoring E:\Temp\imgShow\target\release
> [debug] [2024-07-19T19:56:25.493Z] Locating files E:\Temp\imgShow [2ms]
> [debug] [2024-07-19T19:56:25.495Z] Imported Builder "vercel-rust" from "E:\Temp\imgShow\.vercel\builders\node_modules\vercel-rust"
> [debug] [2024-07-19T19:56:25.495Z] Adding build match for "api/handler" with "vercel-rust@4.0.8"
```

Only the `api/handler` be set the build match.

I'm still diving into the `vercel/vercel` source tree. Maybe the maintainer can provide more info on these.

**Comment by ecklf** [comment]
Might not be the prettiest solution, but you can use something like https://github.com/cortesi/modd in the meantime to trigger a rebuild based on a custom glob using `vc build`

**Comment by ecklf** [comment]
I think this discussion should be moved to the other repo, feel free to raise this again once we have functionality in the custom runtime primities.

**Comment by Zxilly** [comment]
I thought there might be a way to provide the cli with what files are relevant to the project, but I didn't find an API for that, do you know anything about it?
