### ISSUE TITLE
Rust version support

### ISSUE THREAD

**Issue by Alexis-Bize** [vercel-community/rust#23]
**Is your feature request related to a problem? Please describe.**
Can not use the `nightly` version of Rust  with `now-rust@2.0.0`.

**Describe the solution you'd like**
Allow version override via `process.env.RUST_VERSION` or an alternative.

**Describe alternatives you've considered**
Using `builds` instead of `functions` in now / vercel JSON file.

**Additional context**
`downloadRustToolchain` (see https://github.com/mike-engel/now-rust/blob/master/src/install-rust.ts#L4) supports a `version` argument, but isn't / can not be used.

Thank you!

**Comment by mike-engel** [comment]
This looks like a regression that's been around for a while, probably when they switched config formats for runtimes. I'm happy to support a `RUST_VERSION` variable, but can't promise much time soon to work on it. If you'd like to submit a PR, I'm happy to review it and merge it.

**Comment by Alexis-Bize** [comment]
No worries, I'll try to take a look then 👌Thank you!

**Comment by ecklf** [comment]
We'll be looking into adding support for toolchain overrides via https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.

**Comment by ecklf** [comment]
Added in https://github.com/vercel-community/rust/pull/89/files
