### ISSUE TITLE
How to deploy static Rust to WASM projects?

### ISSUE THREAD

**Issue by cryptoquick** [vercel-community/rust#60]
Currently we have to run wasm-pack and commit build artifacts to the repo in order for them to be deployed by Vercel CI. Is there a way to avoid doing that for a Rust WASM static frontend?

**Comment by dglsparsons** [comment]
Hey @cryptoquick - thanks for raising this. I'm not super familiar with wasm-pack so may be off the mark here, but I'm not following the issue with building inside Vercel? Is it just that there are no Rust dependencies pre-installed on the Vercel runners so it would require quite some setup?

**Comment by cryptoquick** [comment]
We eventually learned how to bundle wasm builds and deploy them to NPM. That approach works fine for us.
