### ISSUE TITLE
rust api in nextjs app?

### ISSUE THREAD

**Issue by YuriGor** [vercel-community/rust#69]
Hi all, is there any normal way to have rust api within nextjs app?
In nextjs all the APIs are supposed to be in /pages/api/

If I try to add `/api` alongside with `/pages/api`
`/api` - works, but `/pages/api` doesn't

If I try to place rust code in `/pages/api` and in vercel.json set:
```json
{
  "functions": {
    "pages/api/**/*.rs": {
      "runtime": "vercel-rust@3.1.2"
    }
}
```
it doesn't work, rs file is not compiling.

If I try to move everything under /api from /pages/api - multiple issues with webpack/fetch/next-XXX plugins appear.

Maybe there is some more vercel or nextjs configs I can use?

Or wasm is only option in my case? (except creating separate API project only for Rust)

**Comment by abcd-ca** [comment]
I also encountered this issue. I tested a non-nextjs app and ran it with `vercel dev` and it worked. I could not get a rust api to work in nextjs at all even when trying to relocate the /api dir.

**Comment by ecklf** [comment]
Hey we released a new runtime in https://github.com/vercel-community/rust/pull/80 which now also provides examples to integrate with Next.js. Happy about every feedback.

**Comment by abcd-ca** [comment]
Just did a quick smoke test. Much better, good job, thanks!
