### ISSUE TITLE
Has the project been abandoned ?

### ISSUE THREAD

**Issue by ArthurianX** [vercel-community/rust#71]
I see the latest update was more than a year ago. 
Does the project still have maintainers ?

**Comment by ArthurianX** [comment]
It does look like this project has been abandoned 😬

**Comment by williamboman** [comment]
It's a community project so I wouldn't expect people to monitor issues very closely. It does seem slightly abandoned on the surface tbh but I've not had any issues whatsoever so far. Is there some specific issue you're looking to have solved or is it just the commit traffic itself?

**Comment by spiceee** [comment]
An outstanding PR waiting to be merged adds async support to lambda handles. Rust endpoints with no async support are kinda useless :)

**Comment by williamboman** [comment]
Ah I see, yeah that PR seems very unattended. I'd however argue that async runtimes is far from a deal breaker due to the nature of AWS Lambdas, and you can always terminate async runtimes within your handler.

**Comment by spiceee** [comment]
But at least in Vercel, the `main` function has to be async in order to use stuff like `tokio`, which the AWS SDK for Rust uses too, btw. I haven't figured out a way to spawn threads in Vercel without an async `main`.

**Comment by ecklf** [comment]
Hey we released a new runtime in https://github.com/vercel-community/rust/pull/80 which is based on the latest AWS Rust runtime. Happy about every feedback. I'll look into maintaining this for the foreseeable future.
