### ISSUE TITLE
Add message that Rust is currently building to deploy log

### ISSUE THREAD

**Issue by bram-dingelstad** [vercel-community/rust#73]
When pushing a project through Git with the Vercel builder, it seems to install the rust builder, but then fail to move past the installation of Rust.

<img width="885" alt="Screenshot 2022-11-13 at 2 57 45 PM" src="https://user-images.githubusercontent.com/3514405/201525591-f32fe2b1-17cd-4320-a047-473ba7e30e02.png">

The code I use is available [here](https://github.com/bram-dingelstad/mastodon-tools/tree/16d80c40e395d7b346fab2fc335ad26917f720b8)

It works by rebuilding the project again using the same build cache (since Rust is now installed). I would love this to work in one go though :/

**Comment by bram-dingelstad** [comment]
My apologies, it seems it does work. It just didn't the entirety of last night which is why I wrote the report.
Perhaps some log messages it's starting to build would be helpful? Otherwise it just seems like it's stuck.

**Comment by ecklf** [comment]
I'll close this for housekeeping purposes as this issue was created prior to the reworked runtime. Feel free to re-open if your issue isn't resolved.
