### ISSUE TITLE
What is the large file being uploaded?

### ISSUE THREAD

**Issue by abcd-ca** [vercel-community/rust#78]
```
Vercel CLI 28.11.0
⠼ Uploading [=====---------------] (30.5MB/118.5MB)
```

I am wondering what the 118.5MB file is and what the implications are for Vercel paid plan limits and runtime size/footprint?

**Comment by ecklf** [comment]
This might be your `target` folder. Did you add it to your `.vercelignore`?

**Comment by ecklf** [comment]
I'll close this for housekeeping purposes as this issue was created prior to the reworked runtime. Feel free to re-open if your issue isn't resolved.

**Comment by abcd-ca** [comment]
It's much nicer now and the original issue is resolved, thanks! Good work!
