### ISSUE TITLE
Vercel cannot find serverless functions

### ISSUE THREAD

**Issue by timurguvenkaya** [vercel-community/rust#92]
The pattern "src/api/**/*.rs" defined in `functions` doesn't match any Serverless Functions.

I have my next.js app inside of src/. To test rust runtime I created and put api/ folder inside of src. 

Path to function: src/api/rust.rs

vercel-dev for some reason cannot detect it. When I move it out of src to api/rust.rs, it works.  Am I missing something?

**Comment by ecklf** [comment]
This is a requirement of Vercel CLI, unrelated to the runtime.

Consider creating an issue here that this should be more descriptive:
https://github.com/vercel/vercel
